import time
from datetime import datetime
from io import BytesIO
from pydub import AudioSegment

from fastapi import FastAPI, Response, HTTPException
from pydantic import BaseModel
import uvicorn
import argparse
import warnings

warnings.simplefilter("ignore")

from tts_service.melo_synthesizer import init_melo_synthesizer
from tts_service.piper_synthesizer import init_piper_synthesizer

parser = argparse.ArgumentParser(description="Speech-to-Text Server")
parser.add_argument("--host", type=str, default="0.0.0.0", help="Server host")
parser.add_argument("--port", type=int, default=8000, help="Server port")
args = parser.parse_args()

melo_model = init_melo_synthesizer()
piper_model = init_piper_synthesizer(exclude=melo_model.supported_languages())
models = [melo_model, piper_model]

app = FastAPI()

class TTSRequest(BaseModel):
    language: str
    text: str
    format: str


def write_time(time):
    print("Generated by", time, "seconds")
    if time > 1.0:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open("logs.txt", "a") as f:
            result = now + ": generated by " + str(time) + " seconds\n"
            f.write(result)

supported_mime_types = {
    "wav": "audio/wav",
    "mp3": "audio/mpeg",
    "ogg": "audio/ogg",
    "flac": "audio/flac",
    "aac": "audio/aac",
    "m4a": "audio/mp4",
    "opus": "audio/opus"
}

def convert_audio(audio_buffer: BytesIO, target_format: str) -> BytesIO:
    audio = AudioSegment.from_file(audio_buffer, format="wav")
    out_buffer = BytesIO()
    audio.export(out_buffer, format=target_format)
    out_buffer.seek(0)
    return out_buffer

@app.post("/tts/synthesize/")
def generate_tts(request: TTSRequest):
    lang = request.language
    fmt = request.format.lower()

    if fmt not in supported_mime_types:
        raise HTTPException(status_code=400, detail=f"Unsupported format '{fmt}'")

    model = next((m for m in models if m.has_lan(lang)), None)

    if model is None: raise HTTPException(status_code=400, detail=f"Language '{lang}' is not supported")

    print(f"🎤 Generate audio ({lang}): {request.text}")
    start_time = time.time()
    audio_buffer = model.synthesize(lang, request.text)

    write_time(time.time() - start_time)

    if fmt != "wav":
        audio_buffer = convert_audio(audio_buffer, fmt)

    return Response(content=audio_buffer.read(), media_type=mime_types[fmt])


if __name__ == "__main__":
    uvicorn.run(app, host=args.host, port=args.port)
