import argparse
import os
import time
import warnings
from datetime import datetime
from threading import Lock, Thread
from typing import Union

from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel
import uvicorn

from tts_service.melo_synthesizer import init_melo_synthesizer
from tts_service.piper_synthesizer import init_piper_synthesizer
from utils import (
    audio_type_supported,
    convert_audio,
    get_default_mime_type,
    get_public_media_type,
    normalize_audio_type,
)

warnings.simplefilter("ignore")

DEFAULT_SLOW_REQUEST_SECONDS = 1.0

app = FastAPI()

parser = argparse.ArgumentParser(description="Text-to-Speech Server")
parser.add_argument("--host", type=str, default=os.getenv("HOST", "0.0.0.0"), help="Server host")
parser.add_argument("--port", type=int, default=int(os.getenv("PORT", "8000")), help="Server port")
parser.add_argument(
    "--slow-request-seconds",
    type=float,
    default=float(os.getenv("SLOW_REQUEST_SECONDS", DEFAULT_SLOW_REQUEST_SECONDS)),
    help="Threshold for logging slow requests",
)
parser.add_argument(
    "--default-media-type",
    type=str,
    default=os.getenv("DEFAULT_MEDIA_TYPE", get_default_mime_type()),
    help="Default response media type",
)
args = parser.parse_args()

models = []
models_ready = False
models_load_error = None
models_lock = Lock()
models_loading_started = False


class TTSRequest(BaseModel):
    language: str
    text: str
    mediaType: Union[str, None] = None


def write_time(request_time: float):
    print("generated by", request_time, "seconds")
    if request_time > args.slow_request_seconds:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open("logs.txt", "a", encoding="utf-8") as file:
            file.write(now + ": generated by " + str(request_time) + " seconds\n")


def supported_languages():
    all_languages = set()
    for model in models:
        all_languages.update(model.supported_languages())
    return sorted(all_languages)


def load_models_once():
    global models
    global models_ready
    global models_load_error
    global models_loading_started

    with models_lock:
        if models_ready or models_load_error is not None or models_loading_started:
            return
        models_loading_started = True

    try:
        print("Initialize Melo models")
        melo_model = init_melo_synthesizer()

        print("Initialize Piper models")
        piper_model = init_piper_synthesizer(exclude=melo_model.supported_languages())

        loaded_models = [melo_model, piper_model]

        with models_lock:
            models = loaded_models
            models_ready = True

        print("TTS models initialized:", ", ".join(supported_languages()))
    except Exception as exc:
        with models_lock:
            models_load_error = exc
        print("Failed to initialize TTS models:", exc)


def ensure_models_loading_started():
    with models_lock:
        already_started = models_loading_started or models_ready or models_load_error is not None

    if already_started:
        return

    loader_thread = Thread(target=load_models_once, daemon=True)
    loader_thread.start()


@app.on_event("startup")
async def startup_event():
    ensure_models_loading_started()


@app.get("/ping")
async def ping():
    if models_ready:
        return {"status": "healthy", "languages": supported_languages()}

    if models_load_error is not None:
        raise HTTPException(status_code=500, detail=f"Model initialization failed: {models_load_error}")

    ensure_models_loading_started()
    return Response(status_code=204)


@app.post("/tts/synthesize/")
def generate_tts(request: TTSRequest):
    if models_load_error is not None:
        raise HTTPException(status_code=500, detail=f"Model initialization failed: {models_load_error}")

    if not models_ready:
        raise HTTPException(status_code=503, detail="Models are still initializing")

    mime_type = normalize_audio_type(request.mediaType)
    if mime_type is None:
        mime_type = normalize_audio_type(args.default_media_type)

    if mime_type is None or not audio_type_supported(mime_type):
        raise HTTPException(status_code=400, detail=f"Unsupported format '{request.mediaType}'")

    model = next((item for item in models if item.has_lan(request.language)), None)
    if model is None:
        raise HTTPException(status_code=400, detail=f"Language '{request.language}' is not supported")

    print(f"Generate audio ({request.language}): {request.text}")
    start_time = time.time()
    audio_buffer = model.synthesize(request.language, request.text)

    write_time(time.time() - start_time)

    audio_buffer = convert_audio(audio_buffer, mime_type)

    return Response(content=audio_buffer.read(), media_type=get_public_media_type(mime_type))


if __name__ == "__main__":
    uvicorn.run(app, host=args.host, port=args.port)
