import argparse
import copy
import logging
import time
import warnings
from typing import Union

from fastapi import FastAPI, HTTPException, Response
from pydantic import BaseModel
import uvicorn

from config import get_default_media_type, get_host, get_port
from tts_service.melo_synthesizer import init_melo_synthesizer
from tts_service.piper_synthesizer import init_piper_synthesizer
from utils import (
    audio_type_supported,
    convert_audio,
    get_public_media_type,
    normalize_audio_type,
)

warnings.simplefilter("ignore")

app = FastAPI()

parser = argparse.ArgumentParser(description="Text-to-Speech Server")
parser.add_argument("--host", type=str, default=get_host(), help="Server host")
parser.add_argument("--port", type=int, default=get_port(), help="Server port")
args = parser.parse_args()


class HealthCheckAccessFilter(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        message = record.getMessage()
        return '"GET /ping HTTP/1.1" 200' not in message and '"GET /ping HTTP/1.1" 204' not in message


def build_log_config():
    log_config = copy.deepcopy(uvicorn.config.LOGGING_CONFIG)
    access_logger = log_config["loggers"].get("uvicorn.access")
    if access_logger is None:
        return log_config

    log_config.setdefault("filters", {})
    log_config["filters"]["health_check_access_filter"] = {
        "()": HealthCheckAccessFilter,
    }
    access_logger["filters"] = ["health_check_access_filter"]
    return log_config


class TTSRequest(BaseModel):
    language: str
    text: str
    mediaType: Union[str, None] = None


def write_time(request_time: float):
    print("generated by", request_time, "seconds")


def supported_languages():
    all_languages = set()
    for model in models:
        all_languages.update(model.supported_languages())
    return sorted(all_languages)


def load_models():
    print("Initialize Melo models")
    melo_model = init_melo_synthesizer()

    print("Initialize Piper models")
    piper_model = init_piper_synthesizer(exclude=melo_model.supported_languages())

    loaded_models = [melo_model, piper_model]
    print("TTS models initialized:", ", ".join(sorted({
        language
        for model in loaded_models
        for language in model.supported_languages()
    })))
    return loaded_models


models = load_models()


@app.get("/ping")
async def ping():
    return {"status": "healthy", "languages": supported_languages()}


@app.post("/tts/synthesize/")
def generate_tts(request: TTSRequest):
    mime_type = normalize_audio_type(request.mediaType)
    if mime_type is None:
        mime_type = normalize_audio_type(get_default_media_type())

    if mime_type is None or not audio_type_supported(mime_type):
        raise HTTPException(status_code=400, detail=f"Unsupported format '{request.mediaType}'")

    model = next((item for item in models if item.has_lan(request.language)), None)
    if model is None:
        raise HTTPException(status_code=400, detail=f"Language '{request.language}' is not supported")

    print(f"Generate audio ({request.language}): {request.text}")
    start_time = time.time()
    audio_buffer = model.synthesize(request.language, request.text)

    write_time(time.time() - start_time)

    audio_buffer = convert_audio(audio_buffer, mime_type)

    return Response(content=audio_buffer.read(), media_type=get_public_media_type(mime_type))


if __name__ == "__main__":
    uvicorn.run(app, host=args.host, port=args.port, log_config=build_log_config())
